name: Cypress Tests in Docker

on: workflow_dispatch

jobs:
    cypress-tests:
        runs-on: ubuntu-latest
        container:
            image: cypress/included

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Run Cypress tests
              run: npm run test:qauto

            - name: Upload Cypress test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-results
                  path: |
                      cypress/screenshots
                      cypress/videos
    deploy:
        if: ${{ always() }}
        runs-on: ubuntu-latest
        needs: cypress-tests
        permissions:
          pages: write
          id-token: write
        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4
    
          - name: Create docs directory and copy results if they exist
            run: |
              mkdir -p docs
              if [ -d "cypress/screenshots" ]; then cp -R cypress/screenshots docs/; fi
              if [ -d "cypress/videos" ]; then cp -R cypress/videos docs/; fi
              
          - name: Setup Pages
            uses: actions/configure-pages@v5
    
          - name: Upload artifact to Pages
            uses: actions/upload-pages-artifact@v3
            with:
                path: docs

          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
    
