name: Cypress Tests in Docker

on: workflow_dispatch

jobs:
    cypress-tests:
        runs-on: ubuntu-latest
        container:
            image: cypress/included

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Run Cypress tests
              run: npm run test:qauto

            - name: Upload Cypress test results (screenshots/videos if failed)
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-results
                  path: |
                      cypress/screenshots
                      cypress/videos
