name: Cypress Tests in Docker

on: workflow_dispatch

jobs:
    cypress-tests:
        runs-on: ubuntu-latest
        container:
            image: cypress/included

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Run Cypress tests
              run: npm run test:qauto

            - name: Ensure results directory exists
              run: mkdir -p cypress/results

            - name: Generate Cypress HTML report
              run: |
                  npx mochawesome-merge cypress/results/*.json > cypress/results/report.json
                  npx mochawesome-report-generator cypress/results/report.json --reportDir=cypress/reports --reportTitle="Cypress Test Report"

            - name: Upload Cypress test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                 name: cypress-results
                 path: |
                    cypress/reports/
                    cypress/screenshots
                    cypress/videos
                    
    deploy:
        if: ${{ always() }}
        runs-on: ubuntu-latest
        needs: cypress-tests
        permissions:
          pages: write
          id-token: write
        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4
    
          - name: Download Cypress test results
            uses: actions/download-artifact@v4
            with:
              name: cypress-results
              path: docs
              
          - name: Setup Pages
            uses: actions/configure-pages@v5
    
          - name: Upload artifact to Pages
            uses: actions/upload-pages-artifact@v3
            with:
                path: docs

          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
    
